################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Src/audio_stream_dsp \
Core/Startup \
Drivers/CMSIS/DSP/Source/BasicMathFunctions \
Drivers/CMSIS/DSP/Source/CommonTables \
Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
Drivers/CMSIS/DSP/Source/ControllerFunctions \
Drivers/CMSIS/DSP/Source/FastMathFunctions \
Drivers/CMSIS/DSP/Source/FilteringFunctions \
Drivers/CMSIS/DSP/Source/MatrixFunctions \
Drivers/CMSIS/DSP/Source/StatisticsFunctions \
Drivers/CMSIS/DSP/Source/SupportFunctions \
Drivers/CMSIS/DSP/Source/TransformFunctions \
Drivers/Components/adv7533 \
Drivers/Components/ft6x06 \
Drivers/Components/nt35510 \
Drivers/Components/otm8009a \
Drivers/Components/wm8994 \
Drivers/FatFs-main/ffsystem \
Drivers/FatFs-main/src \
Drivers/Log \
Drivers/STM32F7xx_HAL_Driver/Src \
Drivers/disco_bsp \
Drivers/hal_stm_lvgl/tft \
Drivers/hal_stm_lvgl/touchpad \
Drivers/lvgl/src/core \
Drivers/lvgl/src/debugging/monkey \
Drivers/lvgl/src/debugging/sysmon \
Drivers/lvgl/src/debugging/test \
Drivers/lvgl/src/debugging/vg_lite_tvg \
Drivers/lvgl/src/display \
Drivers/lvgl/src/draw/convert/helium \
Drivers/lvgl/src/draw/convert \
Drivers/lvgl/src/draw/convert/neon \
Drivers/lvgl/src/draw/dma2d \
Drivers/lvgl/src/draw/espressif/ppa \
Drivers/lvgl/src/draw/eve \
Drivers/lvgl/src/draw \
Drivers/lvgl/src/draw/nanovg \
Drivers/lvgl/src/draw/nema_gfx \
Drivers/lvgl/src/draw/nxp/g2d \
Drivers/lvgl/src/draw/nxp/pxp \
Drivers/lvgl/src/draw/opengles \
Drivers/lvgl/src/draw/renesas/dave2d \
Drivers/lvgl/src/draw/sdl \
Drivers/lvgl/src/draw/snapshot \
Drivers/lvgl/src/draw/sw/blend/helium \
Drivers/lvgl/src/draw/sw/blend \
Drivers/lvgl/src/draw/sw/blend/neon \
Drivers/lvgl/src/draw/sw/blend/riscv_v \
Drivers/lvgl/src/draw/sw \
Drivers/lvgl/src/draw/vg_lite \
Drivers/lvgl/src/drivers/display/drm \
Drivers/lvgl/src/drivers/display/fb \
Drivers/lvgl/src/drivers/display/ft81x \
Drivers/lvgl/src/drivers/display/ili9341 \
Drivers/lvgl/src/drivers/display/lcd \
Drivers/lvgl/src/drivers/display/nv3007 \
Drivers/lvgl/src/drivers/display/nxp_elcdif \
Drivers/lvgl/src/drivers/display/renesas_glcdc \
Drivers/lvgl/src/drivers/display/st7735 \
Drivers/lvgl/src/drivers/display/st7789 \
Drivers/lvgl/src/drivers/display/st7796 \
Drivers/lvgl/src/drivers/display/st_ltdc \
Drivers/lvgl/src/drivers/draw/eve \
Drivers/lvgl/src/drivers/evdev \
Drivers/lvgl/src/drivers/libinput \
Drivers/lvgl/src/drivers/nuttx \
Drivers/lvgl/src/drivers/opengles/assets \
Drivers/lvgl/src/drivers/opengles/glad/src \
Drivers/lvgl/src/drivers/opengles \
Drivers/lvgl/src/drivers/opengles/opengl_shader \
Drivers/lvgl/src/drivers/qnx \
Drivers/lvgl/src/drivers/sdl \
Drivers/lvgl/src/drivers/uefi \
Drivers/lvgl/src/drivers/wayland \
Drivers/lvgl/src/drivers/windows \
Drivers/lvgl/src/drivers/x11 \
Drivers/lvgl/src/font/binfont_loader \
Drivers/lvgl/src/font/fmt_txt \
Drivers/lvgl/src/font/font_manager \
Drivers/lvgl/src/font/imgfont \
Drivers/lvgl/src/font \
Drivers/lvgl/src/indev \
Drivers/lvgl/src/layouts/flex \
Drivers/lvgl/src/layouts/grid \
Drivers/lvgl/src/layouts \
Drivers/lvgl/src/libs/FT800-FT813 \
Drivers/lvgl/src/libs/barcode \
Drivers/lvgl/src/libs/bin_decoder \
Drivers/lvgl/src/libs/bmp \
Drivers/lvgl/src/libs/ffmpeg \
Drivers/lvgl/src/libs/freetype \
Drivers/lvgl/src/libs/frogfs/src \
Drivers/lvgl/src/libs/fsdrv \
Drivers/lvgl/src/libs/gif \
Drivers/lvgl/src/libs/gltf/gltf_environment \
Drivers/lvgl/src/libs/gltf/gltf_view/assets \
Drivers/lvgl/src/libs/gltf/math \
Drivers/lvgl/src/libs/gstreamer \
Drivers/lvgl/src/libs/libjpeg_turbo \
Drivers/lvgl/src/libs/libpng \
Drivers/lvgl/src/libs/libwebp \
Drivers/lvgl/src/libs/lodepng \
Drivers/lvgl/src/libs/lz4 \
Drivers/lvgl/src/libs/nanovg \
Drivers/lvgl/src/libs/qrcode \
Drivers/lvgl/src/libs/rle \
Drivers/lvgl/src/libs/rlottie \
Drivers/lvgl/src/libs/svg \
Drivers/lvgl/src/libs/tiny_ttf \
Drivers/lvgl/src/libs/tjpgd \
Drivers/lvgl/src/libs/vg_lite_driver/VGLite \
Drivers/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Drivers/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Drivers/lvgl/src \
Drivers/lvgl/src/misc/cache/class \
Drivers/lvgl/src/misc/cache/instance \
Drivers/lvgl/src/misc/cache \
Drivers/lvgl/src/misc \
Drivers/lvgl/src/osal \
Drivers/lvgl/src/others/file_explorer \
Drivers/lvgl/src/others/fragment \
Drivers/lvgl/src/others/translation \
Drivers/lvgl/src/stdlib/builtin \
Drivers/lvgl/src/stdlib/clib \
Drivers/lvgl/src/stdlib \
Drivers/lvgl/src/stdlib/micropython \
Drivers/lvgl/src/stdlib/rtthread \
Drivers/lvgl/src/stdlib/uefi \
Drivers/lvgl/src/themes/default \
Drivers/lvgl/src/themes \
Drivers/lvgl/src/themes/mono \
Drivers/lvgl/src/themes/simple \
Drivers/lvgl/src/tick \
Drivers/lvgl/src/widgets/3dtexture \
Drivers/lvgl/src/widgets/animimage \
Drivers/lvgl/src/widgets/arc \
Drivers/lvgl/src/widgets/arclabel \
Drivers/lvgl/src/widgets/bar \
Drivers/lvgl/src/widgets/button \
Drivers/lvgl/src/widgets/buttonmatrix \
Drivers/lvgl/src/widgets/calendar \
Drivers/lvgl/src/widgets/canvas \
Drivers/lvgl/src/widgets/chart \
Drivers/lvgl/src/widgets/checkbox \
Drivers/lvgl/src/widgets/dropdown \
Drivers/lvgl/src/widgets/gif \
Drivers/lvgl/src/widgets/image \
Drivers/lvgl/src/widgets/imagebutton \
Drivers/lvgl/src/widgets/ime \
Drivers/lvgl/src/widgets/keyboard \
Drivers/lvgl/src/widgets/label \
Drivers/lvgl/src/widgets/led \
Drivers/lvgl/src/widgets/line \
Drivers/lvgl/src/widgets/list \
Drivers/lvgl/src/widgets/lottie \
Drivers/lvgl/src/widgets/menu \
Drivers/lvgl/src/widgets/msgbox \
Drivers/lvgl/src/widgets/objx_templ \
Drivers/lvgl/src/widgets/property \
Drivers/lvgl/src/widgets/roller \
Drivers/lvgl/src/widgets/scale \
Drivers/lvgl/src/widgets/slider \
Drivers/lvgl/src/widgets/span \
Drivers/lvgl/src/widgets/spinbox \
Drivers/lvgl/src/widgets/spinner \
Drivers/lvgl/src/widgets/switch \
Drivers/lvgl/src/widgets/table \
Drivers/lvgl/src/widgets/tabview \
Drivers/lvgl/src/widgets/textarea \
Drivers/lvgl/src/widgets/tileview \
Drivers/lvgl/src/widgets/win \
Drivers/ui_files \

