// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_TabView1 = NULL;lv_obj_t *ui_Spectrotab = NULL;lv_obj_t *ui_Chart1 = NULL;lv_obj_t *ui_Chart1_Xaxis = NULL;lv_obj_t *ui_Chart1_Yaxis1 = NULL;lv_obj_t *ui_Chart1_Yaxis2 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_play1 = NULL;lv_obj_t *ui_play2 = NULL;lv_obj_t *ui_Spinbox1 = NULL;lv_obj_t *ui_Switch1 = NULL;lv_obj_t *ui_Consoletab = NULL;lv_obj_t *ui_TextArea1 = NULL;
// event funtions
void ui_event_TabView1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      switch_tab( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xBAB9CA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_Screen1);
lv_tabview_set_tab_bar_size(ui_TabView1,50);
lv_obj_set_width( ui_TabView1, lv_pct(100));
lv_obj_set_height( ui_TabView1, lv_pct(100));
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x4A1818), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spectrotab = lv_tabview_add_tab(ui_TabView1, "Spectrogram");
lv_obj_set_flex_flow(ui_Spectrotab,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Spectrotab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Spectrotab, lv_color_hex(0x4E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Spectrotab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Spectrotab, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Chart1 = lv_chart_create(ui_Spectrotab);
lv_obj_set_width( ui_Chart1, lv_pct(79));
lv_obj_set_height( ui_Chart1, lv_pct(100));
lv_obj_set_x( ui_Chart1, -18 );
lv_obj_set_y( ui_Chart1, -17 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_BAR);

ui_Chart1_Xaxis = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_Chart1_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_Chart1_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_Chart1_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_Chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_Chart1_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Xaxis, 2 >= 1 ? 2 : 1 );
ui_Chart1_Yaxis1 = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_Chart1_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart1_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_Chart1_Yaxis2 = lv_scale_create( ui_Chart1 );
lv_scale_set_mode( ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_Chart1_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_Chart1_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_Chart1_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_Chart1_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_Chart1, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Panel4 = lv_obj_create(ui_Spectrotab);
lv_obj_set_width( ui_Panel4, lv_pct(20));
lv_obj_set_height( ui_Panel4, lv_pct(100));
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_play1 = ui_play_create(ui_Panel4);
lv_obj_set_x( ui_play1, 0 );
lv_obj_set_y( ui_play1, 0 );

ui_play2 = ui_play_create(ui_Panel4);
lv_obj_set_x( ui_play2, 0 );
lv_obj_set_y( ui_play2, 0 );

ui_Spinbox1 = lv_spinbox_create(ui_Panel4);
lv_obj_set_width( ui_Spinbox1, 96);
lv_obj_set_height( ui_Spinbox1, 42);
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox1, 4, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,9999 );
lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

ui_Switch1 = lv_switch_create(ui_Panel4);
lv_obj_set_width( ui_Switch1, 50);
lv_obj_set_height( ui_Switch1, 25);
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );

ui_Consoletab = lv_tabview_add_tab(ui_TabView1, "Console");
lv_obj_set_flex_flow(ui_Consoletab,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Consoletab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_TextArea1 = lv_textarea_create(ui_Consoletab);
lv_obj_set_width( ui_TextArea1, lv_pct(100));
lv_obj_set_height( ui_TextArea1, lv_pct(100));
lv_obj_set_x( ui_TextArea1, 4 );
lv_obj_set_y( ui_TextArea1, -57 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_CURSOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_CURSOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TabView1, ui_event_TabView1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_TabView1= NULL;
ui_Spectrotab= NULL;
ui_Chart1= NULL;
ui_Panel4= NULL;
ui_play1= NULL;
ui_play2= NULL;
ui_Spinbox1= NULL;
ui_Switch1= NULL;
ui_Consoletab= NULL;
ui_TextArea1= NULL;

}
