// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern void ui_event_TabView1( lv_event_t * e);
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Spectrotab;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Chart1_Xaxis;
extern lv_obj_t *ui_Chart1_Yaxis1;
extern lv_obj_t *ui_Chart1_Yaxis2;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_play1;
extern lv_obj_t *ui_play2;
extern lv_obj_t *ui_Spinbox1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Consoletab;
extern lv_obj_t *ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

