// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_TabView4;
extern lv_obj_t *ui_Spectrotab;
extern lv_obj_t *ui_Chart2;
extern lv_obj_t *ui_Chart2_Xaxis;
extern lv_obj_t *ui_Chart2_Yaxis1;
extern lv_obj_t *ui_Chart2_Yaxis2;
extern lv_obj_t *ui_Consoletab;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Panel5;
extern void ui_event_Start( lv_event_t * e);
extern lv_obj_t *ui_Start;
extern void ui_event_Label1( lv_event_t * e);
extern lv_obj_t *ui_Label1;
extern void ui_event_Stop( lv_event_t * e);
extern lv_obj_t *ui_Stop;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Start;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

