// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project



#include "waveplayer.h"
#include "waverecorder.h"
#include "app_state.h"


extern AUDIO_DEMO_StateMachine     AudioDemo;
extern AUDIO_PLAYBACK_StateTypeDef AudioState;
extern AUDIO_ApplicationTypeDef appli_state;

TS_StateTypeDef  TS_State;


void record_evt(lv_event_t * e)
{
    if (App_Capturing()) {
        App_PostEvent(EVT_RECORD_STOP, 0);
    } else {
        App_PostEvent(EVT_RECORD_START, 0);
    }
}

void test1(lv_event_t * e)
{
	// Your code here
}
