// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

#include "waveplayer.h"
#include "waverecorder.h"


extern AUDIO_DEMO_StateMachine     AudioDemo;
extern AUDIO_PLAYBACK_StateTypeDef AudioState;
extern AUDIO_ApplicationTypeDef appli_state;

TS_StateTypeDef  TS_State;




void record_evt(lv_event_t * e)
{
	// Your code here

	AudioDemo.state = AUDIO_DEMO_IN;
	//AudioState = AUDIO_STATE_RECORD; //this is set in the
	appli_state = APPLICATION_READY;

// Your code here
}

void test1(lv_event_t * e)
{
	// Your code here
}
