// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_play = NULL;lv_obj_t *ui_stop = NULL;lv_obj_t *ui_stop1 = NULL;lv_obj_t *ui_rec1 = NULL;lv_obj_t *ui_rec = NULL;
// event funtions
void ui_event_play_play( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      button_play( e );
}
}

void ui_event_stop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      button_stop( e );
}
}

void ui_event_rec1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      record_button_pressed( e );
      _ui_opacity_set( ui_rec1, 40);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_height( ui_Panel1, lv_pct(70));
lv_obj_set_x( ui_Panel1, 3 );
lv_obj_set_y( ui_Panel1, -112 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Container1);
lv_obj_set_width( ui_Panel2, lv_pct(100));
lv_obj_set_height( ui_Panel2, lv_pct(30));
lv_obj_set_x( ui_Panel2, -455 );
lv_obj_set_y( ui_Panel2, 698 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_play = ui_play_create(ui_Panel2);
lv_obj_set_x( ui_play, -305 );
lv_obj_set_y( ui_play, 160 );

lv_label_set_text(ui_comp_get_child(ui_play, UI_COMP_PLAY_LABEL1),"play");

ui_stop = lv_button_create(ui_Panel2);
lv_obj_set_width( ui_stop, 100);
lv_obj_set_height( ui_stop, 50);
lv_obj_set_x( ui_stop, -117 );
lv_obj_set_y( ui_stop, 170 );
lv_obj_set_align( ui_stop, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_stop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_stop1 = lv_label_create(ui_stop);
lv_obj_set_width( ui_stop1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_stop1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_stop1, LV_ALIGN_CENTER );
lv_label_set_text(ui_stop1,"stop");

ui_rec1 = lv_button_create(ui_Panel2);
lv_obj_set_width( ui_rec1, 100);
lv_obj_set_height( ui_rec1, 50);
lv_obj_set_x( ui_rec1, -107 );
lv_obj_set_y( ui_rec1, 146 );
lv_obj_set_align( ui_rec1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rec1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_rec1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rec = lv_label_create(ui_rec1);
lv_obj_set_width( ui_rec, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rec, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rec, LV_ALIGN_CENTER );
lv_label_set_text(ui_rec,"rec\n");

lv_obj_add_event_cb(ui_play, ui_event_play_play, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_stop, ui_event_stop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rec1, ui_event_rec1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Container1= NULL;
ui_Panel1= NULL;
ui_Panel2= NULL;
ui_play= NULL;
ui_stop= NULL;
ui_stop1= NULL;
ui_rec1= NULL;
ui_rec= NULL;

}
