// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern void ui_event_play_play( lv_event_t * e);
extern lv_obj_t *ui_play;
extern void ui_event_stop( lv_event_t * e);
extern lv_obj_t *ui_stop;
extern lv_obj_t *ui_stop1;
extern void ui_event_rec1( lv_event_t * e);
extern lv_obj_t *ui_rec1;
extern lv_obj_t *ui_rec;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

