// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_play = NULL;lv_obj_t *ui_rec = NULL;lv_obj_t *ui_stop = NULL;lv_obj_t *ui_Button3 = NULL;
// event funtions
void ui_event_play_play( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      test1( e );
}
}

void ui_event_rec_play( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      record_evt( e );
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Screen2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Container2 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, lv_pct(100));
lv_obj_set_height( ui_Container2, lv_pct(100));
lv_obj_set_x( ui_Container2, -50 );
lv_obj_set_y( ui_Container2, -128 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container4 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, lv_pct(80));
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container5 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(100));
lv_obj_set_height( ui_Container5, lv_pct(20));
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_play = ui_play_create(ui_Container5);
lv_obj_set_x( ui_play, 0 );
lv_obj_set_y( ui_play, 0 );

lv_label_set_text(ui_comp_get_child(ui_play, UI_COMP_PLAY_LABEL5),"play");

ui_rec = ui_play_create(ui_Container5);
lv_obj_set_x( ui_rec, 0 );
lv_obj_set_y( ui_rec, 0 );

lv_label_set_text(ui_comp_get_child(ui_rec, UI_COMP_PLAY_LABEL5),"record");

ui_stop = ui_play_create(ui_Container5);
lv_obj_set_x( ui_stop, 0 );
lv_obj_set_y( ui_stop, 0 );

lv_label_set_text(ui_comp_get_child(ui_stop, UI_COMP_PLAY_LABEL5),"stop");

ui_Button3 = ui_play_create(ui_Screen2);
lv_obj_set_x( ui_Button3, 0 );
lv_obj_set_y( ui_Button3, 0 );

lv_obj_add_event_cb(ui_play, ui_event_play_play, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rec, ui_event_rec_play, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Container2= NULL;
ui_Container4= NULL;
ui_Container5= NULL;
ui_play= NULL;
ui_rec= NULL;
ui_stop= NULL;
ui_Button3= NULL;

}
